services:
  uwsgi:
    build: 
      context: .
      dockerfile: Dockerfile.uwsgi
    container_name: ctfn_uwsgi
    restart: always
    volumes:
      - api:/opt/api

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: ctfn_nginx
    restart: always
    volumes:
      - /run/ctfn:/var/opt
      - api:/run/
    depends_on:
      - uwsgi

volumes:
  api:
